# docker-compose.yml
version: "3.9"
services:
  db:
    image: "postgres:15-alpine"
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db_volume:/var/lib/postgresql/data
